### ISSUE TITLE
deprecation warnings `Redis#exists(key)` will return an Integer in redis-rb 4.3

### ISSUE THREAD

**Issue by alexskr** [ncbo/sparql-client#3]
ncbo_cron logs shows deprecation warnings:
`Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/srv/ncbo/ncbo_cron/vendor/bundle/ruby/2.6.0/bundler/gems/sparql-client-2ab48e2b7b2a/lib/sparql/client.rb:419:in `block in cache_invalidate_graph')

**Comment by mdorf** [comment]
replaced: Redis#exists(key) with Redis#exists?(key)

**Comment by mdorf** [comment]
This fix resulted in an failure to create a new submission. Since sparql-client itself does not import redis gem, it uses the redis object injected by the higher libraries. In this case, the redis version that was getting injected by the ontologies_api was 3.3.3, which does not define method `exists?`.

**Comment by mdorf** [comment]
fixed, deployed
